### ISSUE TITLE
Create a Hero Section 

### ISSUE THREAD

**Issue by Khadim-swe** [Khadim-swe/Data-Base-Project#6]
create a hero section with HTML CSS and Javascrip and send me the ss of out put here in the commit section then make a pull request

**Comment by Noor-kanwal** [comment]
Can  you pleas assign me this issue .I would like to work on this.

**Comment by Khadim-swe** [comment]
Alright if you wish to contribute on this issue start working on it and start it after the navbar and send me the ss of out put then you can create the pull request for it
